on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Build sdist and wheel
        run: >
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) &&
          pipx run build ./python

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: python/dist

      - name: Check for packaging errors
        run: pipx run twine check --strict python/dist/*

      - name: Install produced wheel
        uses: ./.github/actions/install_requirements
        with:
          pip-install: python/dist/*.whl

      - name: Test can import from module
        # If more than one module in src/ replace with module name to test
        run: python -c 'from eiger_detector.data.eiger_meta_writer import EigerMetaWriter'
